services:
  barry:
    image: ghcr.io/lxgrf/barrybot:latest
    container_name: barry
    env_file:
      - .env
    volumes:
      - barry_data:/data
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  barry_data:
