name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t lxgrf/botbox:latest .

    - name: Push Docker image to Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker push lxgrf/botbox:latest

    - name: Deploy to Ubuntu device
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/bots/lxbot
          docker stop lxbot|| true
          docker rm lxbpt || true
          docker pull lxgrf/botbox:latest
          docker run -d --name lxbot -v $(pwd)/.env:/app/.env --restart=always lxgrf/botbox:latest