# name: Deploy

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v1

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_PASSWORD }}

#     - name: Build and push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         platforms: linux/amd64,linux/arm64
#         push: true
#         tags: lxgrf/botbox:latest

#     - name: Deploy to Ubuntu device
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: |
#           cd ~/bots/lxbot
#           docker stop lxbot || true
#           docker rm lxbot || true
#           docker pull lxgrf/botbox:latest
#           docker run -d --name lxbot -v $(pwd)/.env:/app/.env --restart=always lxgrf/botbox:latest